import * as path from 'path'
import { requiredJavaMajor } from '../server/javaPolicy'
import { normalizeRemotePath, remoteParentPath } from './remoteMinecraftPolicy'
import type {
  RemoteDeploymentArtifactKind,
  RemoteDeploymentInput,
  RemoteServerOs,
} from './types'

const SAFE_IDENTIFIER = /^[A-Za-z0-9._-]+$/

function text(value: unknown): string {
  return typeof value === 'string' ? value.trim() : ''
}

function boundedText(value: unknown, label: string, maxLength: number): string {
  const normalized = text(value)
  if (!normalized || normalized.length > maxLength || /[\0\r\n]/.test(normalized)) {
    throw new Error(`${label}无效`)
  }
  return normalized
}

export function classifyRemoteDeploymentArtifact(fileName: string): RemoteDeploymentArtifactKind {
  const lowerName = path.basename(fileName).toLowerCase()
  if (lowerName.endsWith('.jar')) {
    return lowerName.includes('installer') ? 'java-installer' : 'direct-jar'
  }
  if (lowerName.endsWith('.zip') || lowerName.endsWith('.tar.gz') || lowerName.endsWith('.tgz')) {
    return 'archive'
  }
  return 'unsupported'
}

export function classifyRemoteCoreArtifact(
  coreId: string,
  fileName: string,
  url = '',
): RemoteDeploymentArtifactKind {
  const normalizedCoreId = coreId.trim().toLowerCase()
  if (normalizedCoreId === 'forge' || normalizedCoreId === 'neoforge' || normalizedCoreId === 'quilt') {
    return 'java-installer'
  }
  try {
    const parsed = new URL(url)
    if (parsed.searchParams.get('category')?.toLowerCase() === 'installer') return 'java-installer'
  } catch {
    // The URL is validated by the downloader; classification can still use the file name.
  }
  return classifyRemoteDeploymentArtifact(fileName)
}

export function deploymentRequiresJava(coreId: string): boolean {
  return coreId.trim().toLowerCase() !== 'bedrock-server'
}

export function remoteArtifactCompatibilityWarning(
  os: RemoteServerOs,
  coreId: string,
  version: string,
): string | null {
  if (coreId.trim().toLowerCase() !== 'bedrock-server') return null
  const normalizedVersion = version.trim().toLowerCase()
  if (normalizedVersion.startsWith('win-') && os !== 'windows') return '所选基岩版服务端仅支持 Windows'
  if (normalizedVersion.startsWith('linux-') && os !== 'linux') return '所选基岩版服务端仅支持 Linux'
  return null
}

export function normalizeRemoteDeploymentInput(
  os: RemoteServerOs,
  value: unknown,
): RemoteDeploymentInput {
  if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error('部署参数无效')
  const input = value as Partial<RemoteDeploymentInput>
  const name = boundedText(input.name, '服务器名称', 80)
  const targetPath = normalizeRemotePath(os, input.targetPath)
  if (remoteParentPath(os, targetPath) === null || (os === 'windows' && /^[a-z]:\/$/i.test(targetPath))) {
    throw new Error('不能将磁盘根目录作为部署目录')
  }
  const coreId = boundedText(input.coreId, '核心标识', 100)
  if (!SAFE_IDENTIFIER.test(coreId)) throw new Error('核心标识包含不安全字符')
  const coreName = boundedText(input.coreName, '核心名称', 100)
  const version = boundedText(input.version, '核心版本', 100)
  const remark = text(input.remark) || name
  if (remark.length > 500 || /[\0\r\n]/.test(remark)) throw new Error('服务器备注无效')
  const maxRam = Number(input.maxRam)
  if (!Number.isInteger(maxRam) || maxRam < 512 || maxRam > 131072) throw new Error('服务器内存设置无效')
  const serverPort = Number(input.serverPort)
  if (!Number.isInteger(serverPort) || serverPort < 1 || serverPort > 65535) throw new Error('服务器端口无效')
  if (input.eulaAccepted !== true) throw new Error('必须先接受 Minecraft EULA 才能部署服务器')

  return {
    name,
    targetPath,
    coreId,
    coreName,
    version,
    remark,
    maxRam,
    serverPort,
    eulaAccepted: true,
    startAfterDeploy: input.startAfterDeploy === true,
  }
}

export function requiredDeploymentJavaMajor(version: string): number {
  return requiredJavaMajor(version)
}

function tomlString(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')
}

export function serializeRemoteDeploymentProfile(input: RemoteDeploymentInput): string {
  return [
    '# Generated by MCServerTools',
    `server_name = "${tomlString(input.name)}"`,
    `game_version = "${tomlString(input.version)}"`,
    `core_type = "${tomlString(input.coreId)}"`,
    `core_name = "${tomlString(input.coreName)}"`,
    '',
  ].join('\n')
}
