const assert = require('node:assert/strict')
const test = require('node:test')

const {
  normalizeRemotePath,
  parseRemoteServerProfile,
  remoteBaseName,
  remoteJoin,
  remoteParentPath,
  validateRemoteJarName,
  validateRemoteLaunchSpec,
} = require('../dist/main/remote/remoteMinecraftPolicy.js')
const { detectServerFiles } = require('../dist/main/detect.js')

test('normalizes Linux, macOS, and Windows remote Minecraft paths', () => {
  assert.equal(normalizeRemotePath('linux', '/srv/minecraft/paper/'), '/srv/minecraft/paper')
  assert.equal(normalizeRemotePath('macos', '/Users/alex/Minecraft/Paper/'), '/Users/alex/Minecraft/Paper')
  assert.equal(normalizeRemotePath('windows', 'D:\\Minecraft\\Paper\\'), 'D:/Minecraft/Paper')
  assert.equal(normalizeRemotePath('windows', 'D:\\'), 'D:/')
  assert.equal(remoteJoin('D:/Minecraft/Paper', '.mcstools', 'server.log'), 'D:/Minecraft/Paper/.mcstools/server.log')
  assert.equal(remoteBaseName('/srv/minecraft/paper/'), 'paper')
  assert.equal(remoteParentPath('linux', '/srv/minecraft/paper'), '/srv/minecraft')
  assert.equal(remoteParentPath('linux', '/'), null)
  assert.equal(remoteParentPath('macos', '/Users/alex/Minecraft'), '/Users/alex')
  assert.equal(remoteParentPath('macos', '/'), null)
  assert.equal(remoteParentPath('windows', 'D:/Minecraft/Paper'), 'D:/Minecraft')
  assert.equal(remoteParentPath('windows', 'D:/'), '')
})

test('validates constrained remote launch specifications', () => {
  assert.deepEqual(validateRemoteLaunchSpec(undefined, 'server.jar'), { kind: 'jar', target: 'server.jar' })
  assert.deepEqual(validateRemoteLaunchSpec({ kind: 'java-args', target: 'libraries/net/example/unix_args.txt' }), {
    kind: 'java-args',
    target: 'libraries/net/example/unix_args.txt',
  })
  assert.deepEqual(validateRemoteLaunchSpec({ kind: 'native', target: 'bedrock_server.exe' }), {
    kind: 'native',
    target: 'bedrock_server.exe',
  })
  assert.throws(() => validateRemoteLaunchSpec({ kind: 'native', target: '../server.exe' }))
  assert.throws(() => validateRemoteLaunchSpec({ kind: 'java-args', target: 'run.sh' }))
})

test('rejects relative paths and unsafe jar names', () => {
  assert.throws(() => normalizeRemotePath('linux', 'minecraft/server'))
  assert.throws(() => normalizeRemotePath('macos', 'Users/alex/Minecraft'))
  assert.throws(() => normalizeRemotePath('windows', '\\Minecraft\\Server'))
  assert.throws(() => validateRemoteJarName('../server.jar'))
  assert.throws(() => validateRemoteJarName('server.txt'))
  assert.equal(validateRemoteJarName('paper-1.21.1.jar'), 'paper-1.21.1.jar')
})

test('detects a remote server jar from directory entries', () => {
  assert.deepEqual(detectServerFiles([
    { name: 'library.jar', size: 50_000_000 },
    { name: 'paper-1.21.1.jar', size: 40_000_000 },
  ]), {
    jarName: 'paper-1.21.1.jar',
    coreId: 'paper',
    coreName: 'Paper',
    version: '1.21.1',
    jarFiles: ['library.jar', 'paper-1.21.1.jar'],
  })
})

test('parses metadata used to prefill a remote Minecraft server', () => {
  assert.deepEqual(parseRemoteServerProfile(`
# Generated by MCServerTools
server_name = "生存主服"
game_version = "1.21.1"
core_type = "paper"
core_name = "Paper"
ignored = "value"
`), {
    serverName: '生存主服',
    gameVersion: '1.21.1',
    coreType: 'paper',
    coreName: 'Paper',
  })
})
