import { ChildProcess, spawn } from 'child_process'
import { BrowserWindow } from 'electron'
import * as fs from 'fs'
import * as path from 'path'
import { resolveJava } from '../java'
import { requiredJavaMajor } from './javaPolicy'

interface ServerConfig {
  serverId: string
  serverDir: string
  jarPath: string
  jarName: string
  version: string
  maxRam: number
  javaPath?: string
  extraArgs?: string[]
}

export type ServerProcessStatus = 'starting' | 'running' | 'stopping' | 'stopped' | 'error'

export interface ServerRuntimeState {
  serverId: string | null
  status: ServerProcessStatus
}

export class ServerManager {
  private process: ChildProcess | null = null
  private config: ServerConfig | null = null
  private mainWindow: BrowserWindow | null = null
  private status: ServerProcessStatus = 'stopped'
  private forceStopTimer: NodeJS.Timeout | null = null

  setWindow(win: BrowserWindow) { this.mainWindow = win }
  get running() { return this.process !== null }

  getState(): ServerRuntimeState {
    return { serverId: this.process ? this.config?.serverId || null : null, status: this.status }
  }

  private emitLog(line: string, serverId = this.config?.serverId || null) {
    this.mainWindow?.webContents.send('server:log', { serverId, line })
  }

  private emitStatus(status: ServerProcessStatus, serverId = this.config?.serverId || null) {
    this.status = status
    this.mainWindow?.webContents.send('server:status', { serverId, status })
  }

  private clearForceStopTimer() {
    if (this.forceStopTimer) clearTimeout(this.forceStopTimer)
    this.forceStopTimer = null
  }

  private ensureEulaAccepted(serverDir: string) {
    const eulaPath = path.join(serverDir, 'eula.txt')
    const eulaContent = [
      '# Generated by Minecraft Server Tools',
      '# By changing the setting below to TRUE you are indicating your agreement to the EULA.',
      '# https://aka.ms/MinecraftEULA',
      'eula=true',
      '',
    ].join('\n')

    fs.mkdirSync(serverDir, { recursive: true })
    try {
      if (!fs.existsSync(eulaPath) || !/^\s*eula\s*=\s*true\s*$/im.test(fs.readFileSync(eulaPath, 'utf8'))) {
        fs.writeFileSync(eulaPath, eulaContent, 'utf8')
        this.emitLog('[MST] 已自动写入 eula.txt 并同意 EULA')
      }
    } catch (error) {
      this.emitLog(`[MST] 写入 eula.txt 失败: ${error instanceof Error ? error.message : String(error)}`)
    }
  }

  async start(config: ServerConfig): Promise<void> {
    if (this.process) {
      if (this.config?.serverId === config.serverId) return
      throw new Error('已有其他服务器正在运行，请先停止后再启动')
    }
    if (!fs.existsSync(config.jarPath) || !fs.statSync(config.jarPath).isFile()) {
      throw new Error(`找不到服务端 JAR: ${config.jarPath}`)
    }

    const minimumJava = requiredJavaMajor(config.version)
    const javaInfo = resolveJava(config.javaPath, minimumJava)
    if (!javaInfo) throw new Error(`当前服务器需要 Java ${minimumJava} 或更高版本，请在 Java 管理中安装或重新选择`)

    this.config = config
    this.ensureEulaAccepted(config.serverDir)
    const args = [
      `-Xmx${config.maxRam}M`,
      '-jar',
      config.jarPath,
      'nogui',
      ...(config.extraArgs || []),
    ]

    this.emitStatus('starting', config.serverId)
    this.emitLog(`[MST] 使用 Java: ${javaInfo.path} (${javaInfo.version})`, config.serverId)
    this.emitLog(`[MST] 启动命令: ${javaInfo.path} ${args.join(' ')}`, config.serverId)

    const child = spawn(javaInfo.path, args, {
      cwd: config.serverDir,
      stdio: ['pipe', 'pipe', 'pipe'],
      windowsHide: true,
    })
    this.process = child

    child.stdout?.on('data', (data: Buffer) => {
      data.toString().split(/\r?\n/).filter(Boolean).forEach(line => this.emitLog(line, config.serverId))
    })
    child.stderr?.on('data', (data: Buffer) => {
      data.toString().split(/\r?\n/).filter(Boolean).forEach(line => this.emitLog(`[ERR] ${line}`, config.serverId))
    })
    child.on('close', (code) => {
      if (this.process !== child) return
      this.clearForceStopTimer()
      this.emitLog(`[MST] 服务端进程已退出 (code: ${code})`, config.serverId)
      this.process = null
      this.config = null
      this.emitStatus('stopped', config.serverId)
    })

    await new Promise<void>((resolve, reject) => {
      const onSpawn = () => {
        child.off('error', onInitialError)
        child.on('error', error => {
          if (this.process !== child) return
          this.emitLog(`[MST] 进程错误: ${error.message}`, config.serverId)
          this.emitStatus('error', config.serverId)
        })
        this.emitStatus('running', config.serverId)
        resolve()
      }
      const onInitialError = (error: Error) => {
        child.off('spawn', onSpawn)
        if (this.process === child) {
          this.process = null
          this.config = null
        }
        this.emitLog(`[MST] 启动失败: ${error.message}`, config.serverId)
        this.emitStatus('error', config.serverId)
        reject(error)
      }
      child.once('spawn', onSpawn)
      child.once('error', onInitialError)
    })
  }

  stop(serverId: string): void {
    this.assertActiveServer(serverId)
    if (!this.process) return
    this.emitStatus('stopping', serverId)
    this.emitLog('[MST] 正在关闭服务端...', serverId)
    this.process.stdin?.write('stop\n')
    this.clearForceStopTimer()
    this.forceStopTimer = setTimeout(() => this.forceStop(serverId), 10000)
  }

  forceStop(serverId: string): void {
    this.assertActiveServer(serverId)
    this.clearForceStopTimer()
    if (this.process) {
      this.emitLog('[MST] 强制关闭服务端进程', serverId)
      this.process.kill('SIGKILL')
    }
  }

  sendCommand(serverId: string, command: string): void {
    this.assertActiveServer(serverId)
    if (!this.process?.stdin) throw new Error('服务器控制台不可用')
    const value = typeof command === 'string' ? command.trim() : ''
    if (!value || /[\r\n]/.test(value) || value.length > 4096) throw new Error('服务器命令无效')
    this.process.stdin.write(`${value}\n`)
  }

  private assertActiveServer(serverId: string) {
    if (!this.process || !this.config) throw new Error('当前没有正在运行的服务器')
    if (this.config.serverId !== serverId) throw new Error('所选服务器当前没有运行')
  }

  async shutdown(): Promise<void> {
    if (!this.process || !this.config) return
    const child = this.process
    const serverId = this.config.serverId
    try {
      this.stop(serverId)
    } catch {
      child.kill('SIGKILL')
    }
    await new Promise<void>((resolve) => {
      const timer = setTimeout(() => {
        if (this.process === child) child.kill('SIGKILL')
        resolve()
      }, 5000)
      child.once('close', () => {
        clearTimeout(timer)
        resolve()
      })
    })
  }
}
